Add Plotly example
r-wasm/webr pull request #290
Opened 2023-10-06 06:01 UTC by bugzpodder

This adds a Plotly.js example.

You can view the live example here: 
https://pyscript.com/@bugzpodder/fancy-wind/latest

2023-10-16 10:21 UTC, georgestagg requested changes
I like this example of using `ggplot2` and `plotly` with webR, but I think it can be better handled without sending a custom communication message.

If the reason for the example was less about Plotly and instead about documenting sending custom messages, I personally think it is better not to have an example of sending a custom message using `eval_js()` as I would consider it a little too delicate for general use.

Instead, we should design a function to be added to the `webr` R package that deals with the required string interpolation behind the scenes. With this, the `chan.write()` JS function would be an internal implementation detail that R programmer does not need to know about.

2023-10-16 10:21 UTC, georgestagg commented on src/docs/examples.qmd
> +    });
I think this would be better handled using [`webR.evalRString`](https://docs.r-wasm.org/webr/latest/evaluating.html#returning-javascript-values-when-evaluating-r-code):

```suggestion
      const plotlyData = await webR.evalRString(`
library(plotly)
library(ggplot2)

p <- ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point()

plotly_json(p, pretty = FALSE)
`);
      outElem.replaceChildren();
      Plotly.newPlot('out', JSON.parse(plotlyData ), {});
```

2023-10-17 03:03 UTC, bugzpodder commented
Thanks I committed your suggestion and verified it in the link.
I personally use the following function since I prefer to deal with plotly and canvas using the same way using webR.flush():
```
plotly_chart = function (p) {
  library(plotly)
  json <- plotly::plotly_json(p, pretty=FALSE)
  webr::eval_js(paste0(
    "chan.write({",
    "  type: 'webR/plotly',",
    "  data: '",
    gsub("'", "\\\\'", gsub("\\\\", "\\\\\\\\", json)),
    "\',",
    "})"
  ))
}
```

2023-10-17 10:25 UTC, georgestagg approved these changes

2023-10-17 10:25 UTC, merged